export default {
  INTERNAL_ERROR: "FF",
  SUCCESS: "00",
  CREATED: "21",
  NOT_CONTENT: "24",
  INVALID_INPUT: "40",
  UNAUTHORIZED: "41",
  NOT_FOUND: "44",
  NOT_IMPLEMENTED: "51",
  WORKER_ERROR: "91",
};
