export default {
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
  FIRST_NAME: "FIRST_NAME",
  LAST_NAME: "LAST_NAME",
  GENDER: "GENDER",
  ENCRYPTION: "ENCRYPTION",
  IP_ADDRESS: "IP_ADDRESS",
  USER_AGENT: "USER_AGENT",
};
