export enum WordKeysDictionaryEnum {
  EMAIL = "EMAIL",
  PASSWORD = "PASSWORD",
  FIRST_NAME = "FIRST_NAME",
  LAST_NAME = "LAST_NAME",
  GENDER = "GENDER",
  ENCRYPTION = "ENCRYPTION",
  SESSION = "SESSION",
  SESSION_ID = "SESSION_ID",
  SESSION_EXP = "SESSION_EXP",
}
