/**
 * This class Owner is only for demo purposes to use nested objects in the response to map with
 * the OpenAPI schema describer. You can remove it. and resolve the issues generated by the linter.
 */
export class OwnerDto {
  email: string;
  sessionId: string;

  constructor(props: { email: string; sessionId: string }) {
    this.email = props.email;
    this.sessionId = props.sessionId;
  }
}

export class TokenDto {
  token: string;
  expiresIn: number;
  owner: OwnerDto;

  constructor(props: { token: string; expiresIn: number; owner: OwnerDto }) {
    this.token = props.token;
    this.expiresIn = props.expiresIn;
    this.owner = props?.owner;
  }
}
